path: /home/mariopasc/x2go_shared/Datasets/CADICA_Augmented_Labels_Clasificacion/CADICA_Detection_Full
train: images/train  
val: images/val  
test:  images/test

names:
  0: p0_20
  1: p20_50
  2: p50_70
  3: p70_90
  4: p90_98
  5: p99
  6: p100