json_path: "/home/mario/Python/Datasets/COMBINED/tasks/stenosis_detection/datasets/coco/coco_detection.json"
splits_info_path: "/home/mario/Python/Datasets/COMBINED/tasks/stenosis_detection/json/splits.json"
images_root: "/home/mario/Python/Datasets/COMBINED/tasks/stenosis_detection/images"
output_dir: "/home/mario/Python/Datasets/COMBINED/detection"

model_type: "retina_net"
pretrained: true
num_classes: 2
freeze_until: 2

epochs: 5
batch_size: 4
optimizer_type: "adamw"
lr: 0.0001

backbone: "resnet101"  # Options: resnet50, resnet101, mobilenet_v2, efficientnet_b0
fpn_channels: 256
anchor_sizes: [32, 64, 128, 256, 512] # retina_net: [32, 64, 128, 256, 512]
anchor_aspect_ratios: [0.5,1.0,2.0]
nms_threshold: 0.5  # For inference


weight_decay: 0.0005
momentum: 0.9 # for sgd

cos_lr: true
T_0: 10

patience: 10
resume: ""
print_freq: 1
save_freq: -1
