json_path: "/home/mariopasc/Python/Datasets/COMBINED/ICA_DETECTION/datasets/COCO/COCO_coco.json"
splits_info_path: "/home/mariopasc/Python/Datasets/COMBINED/ICA_DETECTION/json_metadata/splits.json"
images_root: "/home/mariopasc/Python/Datasets/COMBINED/ICA_DETECTION/images"
output_dir: "/home/mariopasc/Python/Datasets/COMBINED/ICA_DETECTION/experiments"
model_type: "ssd"
pretrained: true
num_classes: 2
freeze_until: 2
batch_size: 8
epochs: 20
optimizer_type: "adamw"
momentum: 0.9
lr: 0.0001
weight_decay: 0.0005
cos_lr: true
T_0: 10
patience: 10
resume: ""
print_freq: 1
save_freq: -1
