model_source: ultralytics 
model: /home/mpascual/research/tests/angio/yolov8l.pt
data: /home/mpascual/research/datasets/angio/tasks/stenosis_detection/datasets/yolo/yolo_ica_detection.yaml
epochs: 10
img_size: 512
n_trials: 1
save_plots: true
direction: maximize
startup_trials: 0
storage: test_local.db
study_name: test_local
seed: 42
sampler: "ultralytics_es"
output_folder: /home/mpascual/research/tests/angio/ultralytics_es_dca

hyperparameters:
  optimizer:
    type: categorical
    choices: 
      - Adam
      - AdamW
      - NAdam
      - RAdam
  batch:
    type: categorical
    choices: [4, 8, 16, 32, 64]
  lr0:
    type: loguniform
    low: 0.00001
    high: 0.01
  lrf:
    type: loguniform
    low: 0.00001
    high: 0.01
  momentum:
    type: uniform
    low: 0.65
    high: 0.99
  weight_decay:
    type: loguniform
    low: 0.00001
    high: 0.01
  warmup_epochs:
    type: int
    low: 2
    high: 10
  warmup_momentum:
    type: uniform
    low: 0.75
    high: 0.99
  box:
    type: uniform
    low: 6.0
    high: 9.0
  cls:
    type: uniform
    low: 0.3
    high: 0.9
  dfl:
    type: uniform
    low: 0.5
    high: 3.5

