# General Paths
ORIGINAL_INFORMATION_DATASET_CSV_PATH: "/home/mariopasc/Python/Datasets/CADICA_Project/information_dataset.csv"
PROCESSED_DIR: "/home/mariopasc/Python/Datasets/CADICA_Project/Processed_CADICA_Kfold"
SPLITS_CSV_DIR: "/home/mariopasc/Python/Datasets/CADICA_Project/double_cv_splits"

# K-Fold Settings
SEED: 3012022
EXTERNAL_FOLDS: 5
INTERNAL_FOLDS: 1

# Class Mappings
CLASS_MAPPINGS:
  p0_20: 0
  p20_50: 0
  p50_70: 0
  p70_90: 0
  p90_98: 0
  p99: 0
  p100: 0
LABELS_TO_REMOVE: ["p0_20", "p20_50"]

# YOLO Splits
OUTPUT_YOLO_DIR: "/home/mariopasc/Python/Datasets/CADICA_Project/YOLO_Splits"
SYMBOLIC_LINKS: False  # Set to True for symbolic links, False to copy files
