model: /home/mariopasc/x2go_shared/YOLO/yolov8l.pt
data: ./config.yaml
epochs: 1
img_size: 640
n_trials: 1
save_plots: true
storage: CADICA_BHO_TPE.db
study_name: CADICA_TPE_Sampler 

hyperparameters:
  optimizer:
    type: categorical
    choices: 
      - SGD
      - Adam
      - AdamW
      - NAdam
      - RAdam
      - RMSprop
  batch:
    type: categorical
    choices: [4, 8, 16, 32, 64]
  lr0:
    type: loguniform
    low: 0.000001
    high: 0.01
  lrf:
    type: loguniform
    low: 0.000001
    high: 0.01
  momentum:
    type: uniform
    low: 0.55
    high: 0.99
  weight_decay:
    type: loguniform
    low: 0.0000001
    high: 0.01
  warmup_epochs:
    type: int
    low: 0
    high: 5
  warmup_momentum:
    type: uniform
    low: 0.7
    high: 0.99
  box:
    type: uniform
    low: 6.0
    high: 9.0
  cls:
    type: uniform
    low: 0.4
    high: 0.8
  dfl:
    type: uniform
    low: 0.9
    high: 2.5
